services:
  rag-api:
    build: .
    container_name: rag-doc-qa-pro-api
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    extra_hosts:
      - "host.docker.internal:host-gateway"

  rag-ui:
    build: .
    container_name: rag-doc-qa-pro-ui
    command: streamlit run ui/streamlit_app.py --server.port 8501 --server.address 0.0.0.0
    ports:
      - "8501:8501"
    environment:
      - API_BASE=http://rag-api:8000
    depends_on:
      - rag-api
    volumes:
      - ./data:/app/data
